In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import minmax_scale
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PowerTransformer
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from scipy.stats import boxcox
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae
pd.options.display.max_rows = 50

In [2]:
file1 = pd.read_csv('file1.csv')
file2 = pd.read_csv('file2.csv')
file3 = pd.read_csv('file3.csv')

In [3]:
list(file3.columns)

['Customer',
 'State',
 'Customer Lifetime Value',
 'Education',
 'Gender',
 'Income',
 'Monthly Premium Auto',
 'Number of Open Complaints',
 'Policy Type',
 'Total Claim Amount',
 'Vehicle Class']

In [4]:
def rename_columns(file3):
    file3.rename(columns={"Gender":"GENDER", "State":"ST"}, inplace=True)
    return file3

In [5]:
file3_corrected = rename_columns(file3)

In [6]:
list(file3)

['Customer',
 'ST',
 'Customer Lifetime Value',
 'Education',
 'GENDER',
 'Income',
 'Monthly Premium Auto',
 'Number of Open Complaints',
 'Policy Type',
 'Total Claim Amount',
 'Vehicle Class']

In [7]:
list(file1)

['Customer',
 'ST',
 'GENDER',
 'Education',
 'Customer Lifetime Value',
 'Income',
 'Monthly Premium Auto',
 'Number of Open Complaints',
 'Policy Type',
 'Vehicle Class',
 'Total Claim Amount']

In [8]:
list(file2)

['Customer',
 'ST',
 'GENDER',
 'Education',
 'Customer Lifetime Value',
 'Income',
 'Monthly Premium Auto',
 'Number of Open Complaints',
 'Total Claim Amount',
 'Policy Type',
 'Vehicle Class']

In [9]:
def merge():
    file1 = pd.read_csv('file1.csv')
    file2 = pd.read_csv('file2.csv')
    file3_corrected 
    return pd.concat([file1,file2,file3_corrected], axis=0, ignore_index=True)

In [10]:
ca_df = merge()

In [11]:
ca_df

Customer          ST GENDER             Education  \
0      RB50392  Washington    NaN                Master   
1      QZ44356     Arizona      F              Bachelor   
2      AI49188      Nevada      F              Bachelor   
3      WW63253  California      M              Bachelor   
4      GA49547  Washington      M  High School or Below   
...        ...         ...    ...                   ...   
12069  LA72316  California      M              Bachelor   
12070  PK87824  California      F               College   
12071  TD14365  California      M              Bachelor   
12072  UP19263  California      M               College   
12073  Y167826  California      M               College   

      Customer Lifetime Value   Income  Monthly Premium Auto  \
0                         NaN      0.0                1000.0   
1                  697953.59%      0.0                  94.0   
2                 1288743.17%  48767.0                 108.0   
3                  764586.18%      0.0                 106.0   
4                  536307.65%  36357.0                  68.0   
...                       ...      ...                   ...   
12069             23405.98798  71941.0                  73.0   
12070             3096.511217  21604.0                  79.0   
12071             8163.890428      0.0                  85.0   
12072             7524.442436  21941.0                  96.0   
12073             2611.836866      0.0                  77.0   

      Number of Open Complaints     Policy Type  Vehicle Class  \
0                        1/0/00   Personal Auto  Four-Door Car   
1                        1/0/00   Personal Auto  Four-Door Car   
2                        1/0/00   Personal Auto   Two-Door Car   
3                        1/0/00  Corporate Auto            SUV   
4                        1/0/00   Personal Auto  Four-Door Car   
...                         ...             ...            ...   
12069                         0   Personal Auto  Four-Door Car   
12070                         0  Corporate Auto  Four-Door Car   
12071                         3  Corporate Auto  Four-Door Car   
12072                         0   Personal Auto  Four-Door Car   
12073                         0  Corporate Auto   Two-Door Car   

       Total Claim Amount  
0                2.704934  
1             1131.464935  
2              566.472247  
3              529.881344  
4               17.269323  
...                   ...  
12069          198.234764  
12070          379.200000  
12071          790.784983  
12072          691.200000  
12073          369.600000  

[12074 rows x 11 columns]

In [12]:
file3_corrected

Customer          ST  Customer Lifetime Value             Education  \
0     SA25987  Washington              3479.137523  High School or Below   
1     TB86706     Arizona              2502.637401                Master   
2     ZL73902      Nevada              3265.156348              Bachelor   
3     KX23516  California              4455.843406  High School or Below   
4     FN77294  California              7704.958480  High School or Below   
...       ...         ...                      ...                   ...   
7065  LA72316  California             23405.987980              Bachelor   
7066  PK87824  California              3096.511217               College   
7067  TD14365  California              8163.890428              Bachelor   
7068  UP19263  California              7524.442436               College   
7069  Y167826  California              2611.836866               College   

     GENDER  Income  Monthly Premium Auto  Number of Open Complaints  \
0         M       0                   104                          0   
1         M       0                    66                          0   
2         F   25820                    82                          0   
3         F       0                   121                          0   
4         M   30366                   101                          2   
...     ...     ...                   ...                        ...   
7065      M   71941                    73                          0   
7066      F   21604                    79                          0   
7067      M       0                    85                          3   
7068      M   21941                    96                          0   
7069      M       0                    77                          0   

         Policy Type  Total Claim Amount  Vehicle Class  
0      Personal Auto          499.200000   Two-Door Car  
1      Personal Auto            3.468912   Two-Door Car  
2      Personal Auto          393.600000  Four-Door Car  
3      Personal Auto          699.615192            SUV  
4      Personal Auto          484.800000            SUV  
...              ...                 ...            ...  
7065   Personal Auto          198.234764  Four-Door Car  
7066  Corporate Auto          379.200000  Four-Door Car  
7067  Corporate Auto          790.784983  Four-Door Car  
7068   Personal Auto          691.200000  Four-Door Car  
7069  Corporate Auto          369.600000   Two-Door Car  

[7070 rows x 11 columns]

In [13]:
def rename_columns(ca_df):
    ca_df.rename(columns={"ST": "State", "GENDER": "Gender"}, inplace=True)
    return ca_df

In [14]:
rename_columns(ca_df)

Customer       State Gender             Education  \
0      RB50392  Washington    NaN                Master   
1      QZ44356     Arizona      F              Bachelor   
2      AI49188      Nevada      F              Bachelor   
3      WW63253  California      M              Bachelor   
4      GA49547  Washington      M  High School or Below   
...        ...         ...    ...                   ...   
12069  LA72316  California      M              Bachelor   
12070  PK87824  California      F               College   
12071  TD14365  California      M              Bachelor   
12072  UP19263  California      M               College   
12073  Y167826  California      M               College   

      Customer Lifetime Value   Income  Monthly Premium Auto  \
0                         NaN      0.0                1000.0   
1                  697953.59%      0.0                  94.0   
2                 1288743.17%  48767.0                 108.0   
3                  764586.18%      0.0                 106.0   
4                  536307.65%  36357.0                  68.0   
...                       ...      ...                   ...   
12069             23405.98798  71941.0                  73.0   
12070             3096.511217  21604.0                  79.0   
12071             8163.890428      0.0                  85.0   
12072             7524.442436  21941.0                  96.0   
12073             2611.836866      0.0                  77.0   

      Number of Open Complaints     Policy Type  Vehicle Class  \
0                        1/0/00   Personal Auto  Four-Door Car   
1                        1/0/00   Personal Auto  Four-Door Car   
2                        1/0/00   Personal Auto   Two-Door Car   
3                        1/0/00  Corporate Auto            SUV   
4                        1/0/00   Personal Auto  Four-Door Car   
...                         ...             ...            ...   
12069                         0   Personal Auto  Four-Door Car   
12070                         0  Corporate Auto  Four-Door Car   
12071                         3  Corporate Auto  Four-Door Car   
12072                         0   Personal Auto  Four-Door Car   
12073                         0  Corporate Auto   Two-Door Car   

       Total Claim Amount  
0                2.704934  
1             1131.464935  
2              566.472247  
3              529.881344  
4               17.269323  
...                   ...  
12069          198.234764  
12070          379.200000  
12071          790.784983  
12072          691.200000  
12073          369.600000  

[12074 rows x 11 columns]

In [15]:
def lower_columns_labels(ca_df):
    ca_df.columns = [i.lower() for i in ca_df.columns]
    return ca_df

In [16]:
ca_df = lower_columns_labels(ca_df)
ca_df

customer       state gender             education  \
0      RB50392  Washington    NaN                Master   
1      QZ44356     Arizona      F              Bachelor   
2      AI49188      Nevada      F              Bachelor   
3      WW63253  California      M              Bachelor   
4      GA49547  Washington      M  High School or Below   
...        ...         ...    ...                   ...   
12069  LA72316  California      M              Bachelor   
12070  PK87824  California      F               College   
12071  TD14365  California      M              Bachelor   
12072  UP19263  California      M               College   
12073  Y167826  California      M               College   

      customer lifetime value   income  monthly premium auto  \
0                         NaN      0.0                1000.0   
1                  697953.59%      0.0                  94.0   
2                 1288743.17%  48767.0                 108.0   
3                  764586.18%      0.0                 106.0   
4                  536307.65%  36357.0                  68.0   
...                       ...      ...                   ...   
12069             23405.98798  71941.0                  73.0   
12070             3096.511217  21604.0                  79.0   
12071             8163.890428      0.0                  85.0   
12072             7524.442436  21941.0                  96.0   
12073             2611.836866      0.0                  77.0   

      number of open complaints     policy type  vehicle class  \
0                        1/0/00   Personal Auto  Four-Door Car   
1                        1/0/00   Personal Auto  Four-Door Car   
2                        1/0/00   Personal Auto   Two-Door Car   
3                        1/0/00  Corporate Auto            SUV   
4                        1/0/00   Personal Auto  Four-Door Car   
...                         ...             ...            ...   
12069                         0   Personal Auto  Four-Door Car   
12070                         0  Corporate Auto  Four-Door Car   
12071                         3  Corporate Auto  Four-Door Car   
12072                         0   Personal Auto  Four-Door Car   
12073                         0  Corporate Auto   Two-Door Car   

       total claim amount  
0                2.704934  
1             1131.464935  
2              566.472247  
3              529.881344  
4               17.269323  
...                   ...  
12069          198.234764  
12070          379.200000  
12071          790.784983  
12072          691.200000  
12073          369.600000  

[12074 rows x 11 columns]

In [17]:
def discard_column(ca_df):
    ca_df.drop(columns = ["customer"], inplace = True)
    return ca_df

In [18]:
discard_column(ca_df)

state gender             education customer lifetime value  \
0      Washington    NaN                Master                     NaN   
1         Arizona      F              Bachelor              697953.59%   
2          Nevada      F              Bachelor             1288743.17%   
3      California      M              Bachelor              764586.18%   
4      Washington      M  High School or Below              536307.65%   
...           ...    ...                   ...                     ...   
12069  California      M              Bachelor             23405.98798   
12070  California      F               College             3096.511217   
12071  California      M              Bachelor             8163.890428   
12072  California      M               College             7524.442436   
12073  California      M               College             2611.836866   

        income  monthly premium auto number of open complaints  \
0          0.0                1000.0                    1/0/00   
1          0.0                  94.0                    1/0/00   
2      48767.0                 108.0                    1/0/00   
3          0.0                 106.0                    1/0/00   
4      36357.0                  68.0                    1/0/00   
...        ...                   ...                       ...   
12069  71941.0                  73.0                         0   
12070  21604.0                  79.0                         0   
12071      0.0                  85.0                         3   
12072  21941.0                  96.0                         0   
12073      0.0                  77.0                         0   

          policy type  vehicle class  total claim amount  
0       Personal Auto  Four-Door Car            2.704934  
1       Personal Auto  Four-Door Car         1131.464935  
2       Personal Auto   Two-Door Car          566.472247  
3      Corporate Auto            SUV          529.881344  
4       Personal Auto  Four-Door Car           17.269323  
...               ...            ...                 ...  
12069   Personal Auto  Four-Door Car          198.234764  
12070  Corporate Auto  Four-Door Car          379.200000  
12071  Corporate Auto  Four-Door Car          790.784983  
12072   Personal Auto  Four-Door Car          691.200000  
12073  Corporate Auto   Two-Door Car          369.600000  

[12074 rows x 10 columns]

In [19]:
ca_df.dtypes

state                         object
gender                        object
education                     object
customer lifetime value       object
income                       float64
monthly premium auto         float64
number of open complaints     object
policy type                   object
vehicle class                 object
total claim amount           float64
dtype: object

In [20]:
ca_df.education.unique()

array(['Master', 'Bachelor', 'High School or Below', 'College',
       'Bachelors', 'Doctor', nan], dtype=object)

In [21]:
ca_df["vehicle class"].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury SUV', 'Sports Car',
       'Luxury Car', nan], dtype=object)

In [22]:
ca_df["policy type"].unique()

array(['Personal Auto', 'Corporate Auto', 'Special Auto', nan],
      dtype=object)

In [23]:
## Numerical columns: cleaning

ca_df["customer lifetime value"] = ca_df["customer lifetime value"].astype(str).str.replace("%", "")

In [24]:
ca_df["customer lifetime value"].head

<bound method NDFrame.head of 0                nan
1          697953.59
2         1288743.17
3          764586.18
4          536307.65
            ...     
12069    23405.98798
12070    3096.511217
12071    8163.890428
12072    7524.442436
12073    2611.836866
Name: customer lifetime value, Length: 12074, dtype: object>

In [25]:
ca_df['customer lifetime value'] =  pd.to_numeric(ca_df['customer lifetime value'], errors='coerce')

In [26]:
ca_df['customer lifetime value']

0                 NaN
1        6.979536e+05
2        1.288743e+06
3        7.645862e+05
4        5.363077e+05
             ...     
12069    2.340599e+04
12070    3.096511e+03
12071    8.163890e+03
12072    7.524442e+03
12073    2.611837e+03
Name: customer lifetime value, Length: 12074, dtype: float64

In [27]:
ca_df["number of open complaints"] = list(map(lambda x:int(x[2]) if isinstance(x, str) else x, ca_df["number of open complaints"]))

In [28]:
ca_df['number of open complaints'] =  pd.to_numeric(ca_df['number of open complaints'], errors='coerce')

In [29]:
ca_df['number of open complaints'].unique()

array([ 0.,  2.,  1.,  3.,  5.,  4., nan])

In [30]:
ca_df.dtypes

state                         object
gender                        object
education                     object
customer lifetime value      float64
income                       float64
monthly premium auto         float64
number of open complaints    float64
policy type                   object
vehicle class                 object
total claim amount           float64
dtype: object

In [33]:
ca_df = ca_df.drop_duplicates()

In [34]:
ca_df

state gender             education  customer lifetime value  \
0      Washington    NaN                Master                      NaN   
1         Arizona      F              Bachelor             6.979536e+05   
2          Nevada      F              Bachelor             1.288743e+06   
3      California      M              Bachelor             7.645862e+05   
4      Washington      M  High School or Below             5.363077e+05   
...           ...    ...                   ...                      ...   
12069  California      M              Bachelor             2.340599e+04   
12070  California      F               College             3.096511e+03   
12071  California      M              Bachelor             8.163890e+03   
12072  California      M               College             7.524442e+03   
12073  California      M               College             2.611837e+03   

        income  monthly premium auto  number of open complaints  \
0          0.0                1000.0                        0.0   
1          0.0                  94.0                        0.0   
2      48767.0                 108.0                        0.0   
3          0.0                 106.0                        0.0   
4      36357.0                  68.0                        0.0   
...        ...                   ...                        ...   
12069  71941.0                  73.0                        0.0   
12070  21604.0                  79.0                        0.0   
12071      0.0                  85.0                        3.0   
12072  21941.0                  96.0                        0.0   
12073      0.0                  77.0                        0.0   

          policy type  vehicle class  total claim amount  
0       Personal Auto  Four-Door Car            2.704934  
1       Personal Auto  Four-Door Car         1131.464935  
2       Personal Auto   Two-Door Car          566.472247  
3      Corporate Auto            SUV          529.881344  
4       Personal Auto  Four-Door Car           17.269323  
...               ...            ...                 ...  
12069   Personal Auto  Four-Door Car          198.234764  
12070  Corporate Auto  Four-Door Car          379.200000  
12071  Corporate Auto  Four-Door Car          790.784983  
12072   Personal Auto  Four-Door Car          691.200000  
12073  Corporate Auto   Two-Door Car          369.600000  

[8882 rows x 10 columns]

In [36]:
ca_df = ca_df.dropna(how="all")

In [37]:
ca_df

state gender             education  customer lifetime value  \
0      Washington    NaN                Master                      NaN   
1         Arizona      F              Bachelor             6.979536e+05   
2          Nevada      F              Bachelor             1.288743e+06   
3      California      M              Bachelor             7.645862e+05   
4      Washington      M  High School or Below             5.363077e+05   
...           ...    ...                   ...                      ...   
12069  California      M              Bachelor             2.340599e+04   
12070  California      F               College             3.096511e+03   
12071  California      M              Bachelor             8.163890e+03   
12072  California      M               College             7.524442e+03   
12073  California      M               College             2.611837e+03   

        income  monthly premium auto  number of open complaints  \
0          0.0                1000.0                        0.0   
1          0.0                  94.0                        0.0   
2      48767.0                 108.0                        0.0   
3          0.0                 106.0                        0.0   
4      36357.0                  68.0                        0.0   
...        ...                   ...                        ...   
12069  71941.0                  73.0                        0.0   
12070  21604.0                  79.0                        0.0   
12071      0.0                  85.0                        3.0   
12072  21941.0                  96.0                        0.0   
12073      0.0                  77.0                        0.0   

          policy type  vehicle class  total claim amount  
0       Personal Auto  Four-Door Car            2.704934  
1       Personal Auto  Four-Door Car         1131.464935  
2       Personal Auto   Two-Door Car          566.472247  
3      Corporate Auto            SUV          529.881344  
4       Personal Auto  Four-Door Car           17.269323  
...               ...            ...                 ...  
12069   Personal Auto  Four-Door Car          198.234764  
12070  Corporate Auto  Four-Door Car          379.200000  
12071  Corporate Auto  Four-Door Car          790.784983  
12072   Personal Auto  Four-Door Car          691.200000  
12073  Corporate Auto   Two-Door Car          369.600000  

[8881 rows x 10 columns]

In [38]:
ca_df.isna().sum()

state                          0
gender                       122
education                      0
customer lifetime value        7
income                         0
monthly premium auto           0
number of open complaints      0
policy type                    0
vehicle class                  0
total claim amount             0
dtype: int64

In [39]:
ca_df["state"].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'AZ', 'WA'], dtype=object)

In [40]:
ca_df["gender"].unique()

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

In [42]:
ca_df["gender"] = ca_df["gender"].astype(str)

/var/folders/nx/7crq4wx155z00jtfy6fbs9bw0000gn/T/ipykernel_1985/2997091493.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ca_df["gender"] = ca_df["gender"].astype(str)


In [43]:
ca_df["gender"] = list(map(lambda x: "F" if "emal" in x else x, ca_df["gender"]))

/var/folders/nx/7crq4wx155z00jtfy6fbs9bw0000gn/T/ipykernel_1985/1093058908.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ca_df["gender"] = list(map(lambda x: "F" if "emal" in x else x, ca_df["gender"]))


In [44]:
ca_df["gender"] = list(map(lambda x: "M" if "Male" in x else x, ca_df["gender"]))

/var/folders/nx/7crq4wx155z00jtfy6fbs9bw0000gn/T/ipykernel_1985/3456838698.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ca_df["gender"] = list(map(lambda x: "M" if "Male" in x else x, ca_df["gender"]))


In [45]:
ca_df["gender"] = list(map(lambda x: "other" if "nan" in x else x, ca_df["gender"]))

/var/folders/nx/7crq4wx155z00jtfy6fbs9bw0000gn/T/ipykernel_1985/3894935776.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ca_df["gender"] = list(map(lambda x: "other" if "nan" in x else x, ca_df["gender"]))


In [49]:
ca_df["gender"].unique()

array(['other', 'F', 'M'], dtype=object)

In [50]:
ca_df.isna().sum()

state                        0
gender                       0
education                    0
customer lifetime value      7
income                       0
monthly premium auto         0
number of open complaints    0
policy type                  0
vehicle class                0
total claim amount           0
dtype: int64

In [48]:
ca_df[ca_df["customer lifetime value"].isna() == True]

state gender             education  customer lifetime value  \
0     Washington  other                Master                      NaN   
78    Washington      F                Master                      NaN   
988   Washington      M  High School or Below                      NaN   
4333  Washington      M  High School or Below                      NaN   
4380  Washington  other  High School or Below                      NaN   
4588  Washington      M                Master                      NaN   
4869  Washington      F             Bachelors                      NaN   

       income  monthly premium auto  number of open complaints    policy type  \
0         0.0                1000.0                        0.0  Personal Auto   
78    41275.0                  96.0                        0.0  Personal Auto   
988   55561.0                  63.0                        0.0  Personal Auto   
4333  51878.0                  66.0                        1.0  Personal Auto   
4380  36765.0                  66.0                        1.0  Personal Auto   
4588      0.0                  70.0                        0.0  Personal Auto   
4869  25859.0                  74.0                        0.0   Special Auto   

      vehicle class  total claim amount  
0     Four-Door Car            2.704934  
78    Four-Door Car           41.122303  
988   Four-Door Car          227.872071  
4333  Four-Door Car          316.800000  
4380  Four-Door Car          320.849072  
4588  Four-Door Car          336.000000  
4869  Four-Door Car          355.200000

In [55]:
ca_df["customer lifetime value"].mean()

185975.04580793108

In [60]:
ca_df["customer lifetime value"].max()

5816655.35

In [62]:
ca_df["customer lifetime value"].min()

1898.007675

In [ ]:
plt.

In [54]:
ca_df["customer lifetime value"].median()

7772.52637

In [39]:
customer_lifetime_value_mean

8028.8

In [40]:
ca_df["customer lifetime value"] = ca_df["customer lifetime value"].fillna(customer_lifetime_value_mean)

In [41]:
ca_df["customer lifetime value"].unique()

array([8028.8     , 3479.137523, 2502.637401, ..., 8163.890428,
       7524.442436, 2611.836866])

In [42]:
income_mean = round(np.mean(ca_df["income"]), 2)

In [43]:
income_mean

37828.82

In [44]:
ca_df["income"] = ca_df["income"].fillna(income_mean)

In [45]:
ca_df["income"].unique()

array([    0., 48767., 36357., ..., 66367., 71941., 21941.])

In [46]:
monthly_premium_auto_mean = round(np.mean(ca_df["monthly premium auto"]), 2)

In [47]:
monthly_premium_auto_mean

110.39

In [48]:
ca_df["monthly premium auto"] = ca_df["monthly premium auto"].fillna(monthly_premium_auto_mean)

In [49]:
ca_df["monthly premium auto"].unique()

array([ 1000.  ,    94.  ,   108.  ,   106.  ,    68.  ,    69.  ,
          67.  ,   101.  ,    71.  ,    93.  ,   110.  ,    70.  ,
          64.  ,    72.  ,    74.  ,    79.  ,    73.  ,    61.  ,
         111.  ,    80.  ,    63.  ,   237.  ,    65.  ,   130.  ,
          62.  ,   117.  ,    91.  ,    90.  ,    66.  ,    99.  ,
         103.  , 35354.  ,   172.  ,    92.  ,   104.  ,   113.  ,
         124.  ,   105.  ,   100.  ,   112.  ,    97.  ,    95.  ,
         102.  ,    96.  ,   186.  ,    77.  ,    76.  ,   119.  ,
          87.  ,   109.  ,   107.  ,    88.  ,    85.  ,  6464.  ,
         133.  ,    86.  ,    78.  ,    89.  ,   192.  ,   118.  ,
         140.  ,   127.  ,   126.  ,    82.  ,   115.  ,   217.  ,
         114.  ,   138.  ,    81.  ,   255.  ,   150.  ,   123.  ,
         116.  ,   190.  ,    98.  ,   159.  ,    84.  ,    83.  ,
         152.  ,   136.  ,   245.  ,   135.  ,  1005.  ,   225.  ,
         132.  ,   153.  ,   121.  ,   139.  ,   154.  ,   161

In [50]:
number_of_open_complaints_mean = round(np.mean(ca_df["number of open complaints"]), 2)

In [51]:
number_of_open_complaints_mean

0.38

In [52]:
ca_df["number of open complaints"] = ca_df["number of open complaints"].fillna(number_of_open_complaints_mean)

In [53]:
ca_df["number of open complaints"].unique()

array([0.  , 2.  , 1.  , 3.  , 5.  , 4.  , 0.38])

In [54]:
total_claim_amount_mean = round(np.mean(ca_df["total claim amount"]), 2)

In [55]:
ca_df["total claim amount"] = ca_df["total claim amount"].fillna(total_claim_amount_mean)

In [56]:
ca_df["total claim amount"].unique()

array([   2.704934, 1131.464935,  566.472247, ...,  541.282007,
        198.234764,  790.784983])

In [57]:
type(ca_df["state"])

pandas.core.series.Series

In [58]:
## ACTIVITY 2

In [59]:
ca_df["state"] = ca_df["state"].astype("str")

In [60]:
ca_df['state'] = list(map(lambda x: "Arizona" if ("AZ" in x) else x, ca_df["state"]))

In [61]:
ca_df["state"].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'WA', 'nan'], dtype=object)

In [62]:
ca_df['state'] = list(map(lambda x: "Washington" if ("WA" in x) else x, ca_df["state"]))

In [63]:
ca_df['state'] = list(map(lambda x: "California" if ("Cali" in x) else x, ca_df["state"]))

In [64]:
ca_df["state"].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'nan'],
      dtype=object)

In [65]:
ca_df["state"] = ca_df["state"].astype("category")

In [66]:
state_labels_bins = {"California": "West", "Oregon": "North West", "Washington": "East", "Navada": "Central", "Arizona": "Central"} 

In [67]:
str(state_labels_bins)

"{'California': 'West', 'Oregon': 'North West', 'Washington': 'East', 'Navada': 'Central', 'Arizona': 'Central'}"

In [68]:
ca_df['state'].replace(state_labels_bins, inplace = True)

In [69]:
ca_df["state"]

0           East
1        Central
2         Nevada
3           West
4           East
          ...   
12069       West
12070       West
12071       West
12072       West
12073       West
Name: state, Length: 12074, dtype: object

In [70]:
ca_df["state"] = ca_df["state"].str.lower()

In [71]:
ca_df["gender"] = ca_df["gender"].str.lower()

In [72]:
ca_df["education"] = ca_df["education"].str.lower()

In [73]:
ca_df["policy type"] = ca_df["policy type"].str.lower()

In [74]:
ca_df["vehicle class"] = ca_df["vehicle class"].str.lower()

In [75]:
ca_df.head()

state gender             education  customer lifetime value   income  \
0     east  other                master                   8028.8      0.0   
1  central      f              bachelor                   8028.8      0.0   
2   nevada      f              bachelor                   8028.8  48767.0   
3     west      m              bachelor                   8028.8      0.0   
4     east      m  high school or below                   8028.8  36357.0   

   monthly premium auto  number of open complaints     policy type  \
0                1000.0                        0.0   personal auto   
1                  94.0                        0.0   personal auto   
2                 108.0                        0.0   personal auto   
3                 106.0                        0.0  corporate auto   
4                  68.0                        0.0   personal auto   

   vehicle class  total claim amount  
0  four-door car            2.704934  
1  four-door car         1131.464935  
2   two-door car          566.472247  
3            suv          529.881344  
4  four-door car           17.269323

In [36]:
types_columns = select_dtypes(incldataude=None, exclude=None)

NameError: name 'select_dtypes' is not defined